<?php
if($gateSistema=="rs"){
    define("TAB_FAV_DXOCUMENTOSIXTENS","DOCUMENTOSITENS");

    define("COL_FAV_DXIT_DXESCRICAOPRINCIPAL","DIT_DESCRICAOPRINCIPAL");
    define("COL_FAV_DXIT_IXD","DIT_ID");
    define("COL_FAV_DXIT_IXDDXOCUMENTOS","DIT_IDDOCUMENTOS");
    define("COL_FAV_DXIT_IXDIXTEM","DIT_IDITEM");
    define("COL_FAV_DXIT_IXDTXIPODEOPERACAOSTATUS","DIT_IDTIPODEOPERACAOSTATUS");
    define("COL_FAV_DXIT_PXESOBRUTO","DIT_PESOBRUTO");
    define("COL_FAV_DXIT_QXTDCOMERCIAL","DIT_QTDCOMERCIAL");
    define("COL_FAV_DXIT_VXALORUNITARIOCOMERCIAL","DIT_VALORUNITARIOCOMERCIAL");
    define("COL_FAV_DXIT_NXRITEM","DIT_NRITEM");
    define("COL_FAV_DXIT_VXALORDESCONTO","DIT_VALORDESCONTO");
    define("COL_FAV_DXIT_CXODIGOPARTICIPANTE","DIT_CODIGOPARTICIPANTE");

    $COL_FAV_DXIT_IXDTXIPODEOPERACAOSTATUS = array(
        30 => 30,
        31 => 31,
        32 => 32,
        34 => 34
    );
}else if($gateSistema=="petrus"){
    define("TAB_FAV_DXOCUMENTOSIXTENS","I58");

    define("COL_FAV_DXIT_DXESCRICAOPRINCIPAL","I58_DESCRICAO");
    define("COL_FAV_DXIT_IXD","I58_ID");
    define("COL_FAV_DXIT_IXDDXOCUMENTOS","I57_ID");
    define("COL_FAV_DXIT_IXDIXTEM","G6_ID");
    define("COL_FAV_DXIT_IXDTXIPODEOPERACAOSTATUS","");// NÃO TEM ESSE CAMPO NO PETRUS
    define("COL_FAV_DXIT_PXESOBRUTO","I58_PESO_BRUTO");
    define("COL_FAV_DXIT_QXTDCOMERCIAL","I58_QTD");
    define("COL_FAV_DXIT_VXALORUNITARIOCOMERCIAL","I58_VALOR_UNITARIO");
    define("COL_FAV_DXIT_NXRITEM","I58_ITEM");
    define("COL_FAV_DXIT_VXALORDESCONTO","I58_VALOR_DESCONTO");
    define("COL_FAV_DXIT_CXODIGOPARTICIPANTE","I5_ID");
}