<?php
if($gateSistema=="rs"){
    define("TAB_FTR_DXOCUMENTOS","DOCUMENTOS");

    define("COL_FTR_DXOC_DXATACONCLUSAO","DOC_DATACONCLUSAO");
    define("COL_FTR_DXOC_DXATAEMISSAO","DOC_DATAEMISSAO");
    define("COL_FTR_DXOC_IXD","DOC_ID");
    define("COL_FTR_DXOC_IXDEMPRESA","DOC_IDEMPRESA");
    define("COL_FTR_DXOC_IXDPARTICIPANTE","DOC_IDPARTICIPANTE");
    define("COL_FTR_DXOC_IXDREPRESENTANTE","DOC_IDREPRESENTANTE");
    define("COL_FTR_DXOC_IXDTIPODEOPERACAO","DOC_IDTIPODEOPERACAO");
    define("COL_FTR_DXOC_IXDTIPODEOPERACAO_EX","DOC_IDTIPODEOPERACAO");
    define("COL_FTR_DXOC_IXDTIPODEOPERACAOSTATUS","DOC_IDTIPODEOPERACAOSTATUS");// 30, 31, 32, 34 (Aberto, Concluído, Aprovado, Cancelado)
    define("COL_FTR_DXOC_NXRDOCUMENTO","DOC_NRDOCUMENTO");
    define("COL_FTR_DXOC_PXERCENTUALDESCONTOFATURAMENTOESPECIAL","DOC_PERCENTUALDESCONTOFATURAMENTOESPECIAL");
    define("COL_FTR_DXOC_IXDCONDICOESDEPAGAMENTO","DOC_IDCONDICOESDEPAGAMENTO");
    define("COL_FTR_DXOC_IXDCONDICAODEPAGAMENTOESPECIAL","DOC_IDCONDICAODEPAGAMENTOESPECIAL");
    define("COL_FTR_DXOC_CXOMISSAO","DOC_COMISSAO");
    define("COL_FTR_DXOC_IXDTRANSPORTEREDESPACHO","DOC_IDTRANSPORTEREDESPACHO");
    define("COL_FTR_DXOC_IXDTRANSPORTEDEPOSITO","DOC_IDTRANSPORTEDEPOSITO");
    define("COL_FTR_DXOC_DXOC_IDTRANSPORTE","DOC_IDTRANSPORTE");
    define("COL_FTR_DXOC_QUANTIDADE","DOC_QUANTIDADE");
    define("COL_FTR_DXOC_JXUSTIFICATIVA","DOC_JUSTIFICATIVA");
    define("COL_FTR_DXOC_IXDCONDICAOPAGAMENTO","N47_ID");

    $COL_FTR_DXOC_IXDTIPODEOPERACAOSTATUS = array(
        30 => 30,
        31 => 31,
        32 => 32,
        34 => 34,
        258 => 258
    );
}else if($gateSistema=="petrus"){
    define("TAB_FTR_DXOCUMENTOS","I11");

    define("COL_FTR_DXOC_DXATACONCLUSAO","I11_DATA_FATURAMENTO");
    define("COL_FTR_DXOC_DXATAEMISSAO","I11_DATA_EMISSAO");
    define("COL_FTR_DXOC_IXD","I11_ID");
    define("COL_FTR_DXOC_IXDEMPRESA","S1_ID");
    define("COL_FTR_DXOC_IXDPARTICIPANTE","I5_ID");
    define("COL_FTR_DXOC_IXDREPRESENTANTE","R4_ID");
    define("COL_FTR_DXOC_IXDTIPODEOPERACAO","DOC_IDTIPODEOPERACAO");
    define("COL_FTR_DXOC_IXDTIPODEOPERACAO_EX","5 AS DOC_IDTIPODEOPERACAO");
    define("COL_FTR_DXOC_IXDTIPODEOPERACAOSTATUS","I11_STATUS");// 30, 31, 32, 34 (Aberto, Concluído, Aprovado, Cancelado)
    define("COL_FTR_DXOC_NXRDOCUMENTO","I11_NF");
    define("COL_FTR_DXOC_PXERCENTUALDESCONTOFATURAMENTOESPECIAL","I11_TIPO_FATURAMENTO");
    define("COL_FTR_DXOC_IXDCONDICOESDEPAGAMENTO","N47_ID");
    define("COL_FTR_DXOC_IXDCONDICAODEPAGAMENTOESPECIAL","N47_ID_1");
    define("COL_FTR_DXOC_CXOMISSAO","I11_COMISSAO");
    define("COL_FTR_DXOC_IXDTRANSPORTEREDESPACHO","J2_ID_1");
    define("COL_FTR_DXOC_IXDTRANSPORTEDEPOSITO","J2_ID_1");
    define("COL_FTR_DXOC_DXOC_IDTRANSPORTE","J2_ID");
    define("COL_FTR_DXOC_QUANTIDADE","I11_VOLUMES");
    define("COL_FTR_DXOC_JXUSTIFICATIVA","I11_MOTIVO_CANCELAMENTO");
    define("COL_FTR_DXOC_IXDCONDICAOPAGAMENTO","N47_ID");

    $COL_FTR_DXOC_IXDTIPODEOPERACAOSTATUS = array(
        30 => "Novo",
        31 => "Concluido",
        32 => "Autorizado",
        34 => "Cancelado",
        258 => 258
    );

    $de5para35 = array(
        "I11_ID" => "I57_ID",
        "I11_NF" => "I57_NRO_DOCUMENTO",
        "I11_DATA_EMISSAO" => "I57_DATA_EMISSAO",
        "I46_DESCRICAO" => "I58_DESCRICAO",
        "I46_QTD" => "I58_QTD",
        "I46_VALOR_UNITARIO" => "I58_VALOR_UNITARIO",
        "I46_ID" => "I58_ID"
    );
}