<?php
if($gateSistema=="rs"){
    define("TAB_COM_DXOCUMENTOS","DOCUMENTOS");

    define("COL_COM_DXOC_DXATACONCLUSAO","DOC_DATACONCLUSAO");
    define("COL_COM_DXOC_DXATAEMISSAO","DOC_DATAEMISSAO");
    define("COL_COM_DXOC_IXD","DOC_ID");
    define("COL_COM_DXOC_IXDEMPRESA","DOC_IDEMPRESA");
    define("COL_COM_DXOC_IXDPARTICIPANTE","DOC_IDPARTICIPANTE");
    define("COL_COM_DXOC_IXDREPRESENTANTE","DOC_IDREPRESENTANTE");
    define("COL_COM_DXOC_IXDTIPODEOPERACAO","DOC_IDTIPODEOPERACAO");
    define("COL_COM_DXOC_IXDTIPODEOPERACAO_EX","DOC_IDTIPODEOPERACAO");
    define("COL_COM_DXOC_IXDTIPODEOPERACAOSTATUS","DOC_IDTIPODEOPERACAOSTATUS");// 30, 31, 32, 34 (Aberto, Concluído, Aprovado, Cancelado)
    define("COL_COM_DXOC_NXRDOCUMENTO","DOC_NRDOCUMENTO");
    define("COL_COM_DXOC_PXERCENTUALDESCONTOFATURAMENTOESPECIAL","DOC_PERCENTUALDESCONTOFATURAMENTOESPECIAL");
    define("COL_COM_DXOC_IXDCONDICOESDEPAGAMENTO","DOC_IDCONDICOESDEPAGAMENTO");
    define("COL_COM_DXOC_IXDCONDICAODEPAGAMENTOESPECIAL","DOC_IDCONDICAODEPAGAMENTOESPECIAL");
    define("COL_COM_DXOC_CXOMISSAO","DOC_COMISSAO");
    define("COL_COM_DXOC_IXDTRANSPORTEREDESPACHO","DOC_IDTRANSPORTEREDESPACHO");
    define("COL_COM_DXOC_IXDTRANSPORTEDEPOSITO","DOC_IDTRANSPORTEDEPOSITO");
    define("COL_COM_DXOC_DXOC_IDTRANSPORTE","DOC_IDTRANSPORTE");
    define("COL_COM_DXOC_QUANTIDADE","DOC_QUANTIDADE");
    define("COL_COM_DXOC_JXUSTIFICATIVA","DOC_JUSTIFICATIVA");

    $COL_COM_DXOC_IXDTIPODEOPERACAOSTATUS = array(
        30 => 30,
        31 => 31,
        32 => 32,
        34 => 34,
        258 => 258
    );
}else if($gateSistema=="petrus"){
    define("TAB_COM_DXOCUMENTOS","I14");

    define("COL_COM_DXOC_DXATACONCLUSAO","I14_DATA_FATURAMENTO");
    define("COL_COM_DXOC_DXATAEMISSAO","I14_DATA_EMISSAO");
    define("COL_COM_DXOC_IXD","I14_ID");
    define("COL_COM_DXOC_IXDEMPRESA","S1_ID");
    define("COL_COM_DXOC_IXDPARTICIPANTE","I5_ID");
    define("COL_COM_DXOC_IXDREPRESENTANTE","R4_ID");
    define("COL_COM_DXOC_IXDTIPODEOPERACAO","DOC_IDTIPODEOPERACAO");
    define("COL_COM_DXOC_IXDTIPODEOPERACAO_EX","4 AS DOC_IDTIPODEOPERACAO");
    define("COL_COM_DXOC_IXDTIPODEOPERACAOSTATUS","I14_STATUS");// 30, 31, 32, 34 (Aberto, Concluído, Aprovado, Cancelado)
    define("COL_COM_DXOC_NXRDOCUMENTO","I14_NRO_DOCUMENTO");
    define("COL_COM_DXOC_PXERCENTUALDESCONTOFATURAMENTOESPECIAL","I14_TIPO_FATURAMENTO");
    define("COL_COM_DXOC_IXDCONDICOESDEPAGAMENTO","N47_ID");
    define("COL_COM_DXOC_IXDCONDICAODEPAGAMENTOESPECIAL","N47_ID_1");
    define("COL_COM_DXOC_CXOMISSAO","I14_COMISSAO");
    define("COL_COM_DXOC_IXDTRANSPORTEREDESPACHO","J2_ID_1");
    define("COL_COM_DXOC_IXDTRANSPORTEDEPOSITO","J2_ID_1");
    define("COL_COM_DXOC_DXOC_IDTRANSPORTE","J2_ID");
    define("COL_COM_DXOC_QUANTIDADE","I14_VOLUMES");
    define("COL_COM_DXOC_JXUSTIFICATIVA","I14_MOTIVO_CANCELAMENTO");

    $COL_COM_DXOC_IXDTIPODEOPERACAOSTATUS = array(
        30 => "Novo",
        31 => "Concluido",
        32 => "Aprovado",
        34 => "Cancelado",
        258 => 258
    );
}