<?php
if($gateSistema=="rs"){
    define("TAB_VEN_DXOCUMENTOS","DOCUMENTOS");

    define("COL_VEN_DXOC_DXATACONCLUSAO","DOC_DATACONCLUSAO");
    define("COL_VEN_DXOC_DXATAEMISSAO","DOC_DATAEMISSAO");
    define("COL_VEN_DXOC_IXD","DOC_ID");
    define("COL_VEN_DXOC_IXDEMPRESA","DOC_IDEMPRESA");
    define("COL_VEN_DXOC_IXDPARTICIPANTE","DOC_IDPARTICIPANTE");
    define("COL_VEN_DXOC_IXDREPRESENTANTE","DOC_IDREPRESENTANTE");
    define("COL_VEN_DXOC_IXDTIPODEOPERACAO","DOC_IDTIPODEOPERACAO");
    define("COL_VEN_DXOC_IXDTIPODEOPERACAO_EX","DOC_IDTIPODEOPERACAO");
    define("COL_VEN_DXOC_IXDTIPODEOPERACAOSTATUS","DOC_IDTIPODEOPERACAOSTATUS");// 30, 31, 32, 34 (Aberto, Concluído, Aprovado, Cancelado)
    define("COL_VEN_DXOC_NXRDOCUMENTO","DOC_NRDOCUMENTO");
    define("COL_VEN_DXOC_PXERCENTUALDESCONTOFATURAMENTOESPECIAL","DOC_PERCENTUALDESCONTOFATURAMENTOESPECIAL");
    define("COL_VEN_DXOC_IXDCONDICOESDEPAGAMENTO","DOC_IDCONDICOESDEPAGAMENTO");
    define("COL_VEN_DXOC_IXDCONDICAODEPAGAMENTOESPECIAL","DOC_IDCONDICAODEPAGAMENTOESPECIAL");
    define("COL_VEN_DXOC_CXOMISSAO","DOC_COMISSAO");
    define("COL_VEN_DXOC_IXDTRANSPORTEREDESPACHO","DOC_IDTRANSPORTEREDESPACHO");
    define("COL_VEN_DXOC_IXDTRANSPORTEDEPOSITO","DOC_IDTRANSPORTEDEPOSITO");
    define("COL_VEN_DXOC_DXOC_IDTRANSPORTE","DOC_IDTRANSPORTE");
    define("COL_VEN_DXOC_QUANTIDADE","DOC_QUANTIDADE");
    define("COL_VEN_DXOC_JXUSTIFICATIVA","DOC_JUSTIFICATIVA");
    define("EXP_DOC_1","DOCUMENTOS.DOC_ID AND DOCUMENTOSITENS.DIT_IDTIPODEOPERACAOSTATUS=31");
    define("DOC_NRNFE","DOC_NRNFE");

    $COL_DXOC_IXDTIPODEOPERACAOSTATUS = array(
        30 => 30,
        31 => 31,
        32 => 32,
        34 => 34,
        258 => 258
    );
}else if($gateSistema=="petrus"){
    define("TAB_VEN_DXOCUMENTOS","R13");

    define("COL_VEN_DXOC_DXATACONCLUSAO","R13_DATA_FATURAMENTO");
    define("COL_VEN_DXOC_DXATAEMISSAO","R13_DATA_EMISSAO");
    define("COL_VEN_DXOC_IXD","R13_ID");
    define("COL_VEN_DXOC_IXDEMPRESA","S1_ID");
    define("COL_VEN_DXOC_IXDPARTICIPANTE","R2_ID");
    define("COL_VEN_DXOC_IXDREPRESENTANTE","R4_ID");
    define("COL_VEN_DXOC_IXDTIPODEOPERACAO","DOC_IDTIPODEOPERACAO");
    define("COL_VEN_DXOC_IXDTIPODEOPERACAO_EX","2 AS DOC_IDTIPODEOPERACAO");
    define("COL_VEN_DXOC_IXDTIPODEOPERACAOSTATUS","R13_STATUS");// 30, 31, 32, 34 (Aberto, Concluído, Aprovado, Cancelado)
    define("COL_VEN_DXOC_NXRDOCUMENTO","R13_NRO_DOCUMENTO");
    define("COL_VEN_DXOC_PXERCENTUALDESCONTOFATURAMENTOESPECIAL","R13_TIPO_FATURAMENTO");
    define("COL_VEN_DXOC_IXDCONDICOESDEPAGAMENTO","N47_ID");
    define("COL_VEN_DXOC_IXDCONDICAODEPAGAMENTOESPECIAL","N47_ID_1");
    define("COL_VEN_DXOC_CXOMISSAO","R13_COMISSAO");
    define("COL_VEN_DXOC_IXDTRANSPORTEREDESPACHO","J2_ID_1");
    define("COL_VEN_DXOC_IXDTRANSPORTEDEPOSITO","J2_ID_1");
    define("COL_VEN_DXOC_DXOC_IDTRANSPORTE","J2_ID");
    define("COL_VEN_DXOC_QUANTIDADE","R13_VOLUMES");
    define("COL_VEN_DXOC_JXUSTIFICATIVA","R13_MOTIVO_CANCELAMENTO");
    define("COL_VEN_DXOC_FXRETE","R13_FRETE");
    define("EXP_DOC_1","R13.R13_ID");
    define("DOC_NRNFE","R13_NF");
    define("COL_VEN_DXOC_SUBTOTAL","R13_SUBTOTAL");
    define("COL_VEN_DXOC_VALOR_TOTAL","R13_VALOR_TOTAL");

    $COL_DXOC_IXDTIPODEOPERACAOSTATUS = array(
        30 => "Novo",
        31 => "Faturado",
        32 => "Liberado",
        34 => "Cancelado",
        258 => 258
    );
}