<?php
if($gateSistema=="rs"){
    define("TAB_FAV_DXOCUMENTOS","DOCUMENTOS");

    define("COL_FAV_DXOC_DXATACONCLUSAO","DOC_DATACONCLUSAO");
    define("COL_FAV_DXOC_DXATAEMISSAO","DOC_DATAEMISSAO");
    define("COL_FAV_DXOC_IXD","DOC_ID");
    define("COL_FAV_DXOC_IXDEMPRESA","DOC_IDEMPRESA");
    define("COL_FAV_DXOC_IXDPARTICIPANTE","DOC_IDPARTICIPANTE");
    define("COL_FAV_DXOC_IXDREPRESENTANTE","DOC_IDREPRESENTANTE");
    define("COL_FAV_DXOC_IXDTIPODEOPERACAO","DOC_IDTIPODEOPERACAO");
    define("COL_FAV_DXOC_IXDTIPODEOPERACAO_EX","DOC_IDTIPODEOPERACAO");
    define("COL_FAV_DXOC_IXDTIPODEOPERACAOSTATUS","DOC_IDTIPODEOPERACAOSTATUS");// 30, 31, 32, 34 (Aberto, Concluído, Aprovado, Cancelado)
    define("COL_FAV_DXOC_NXRDOCUMENTO","DOC_NRDOCUMENTO");
    define("COL_FAV_DXOC_PXERCENTUALDESCONTOFATURAMENTOESPECIAL","DOC_PERCENTUALDESCONTOFATURAMENTOESPECIAL");
    define("COL_FAV_DXOC_IXDCONDICOESDEPAGAMENTO","DOC_IDCONDICOESDEPAGAMENTO");
    define("COL_FAV_DXOC_IXDCONDICAODEPAGAMENTOESPECIAL","DOC_IDCONDICAODEPAGAMENTOESPECIAL");
    define("COL_FAV_DXOC_CXOMISSAO","DOC_COMISSAO");
    define("COL_FAV_DXOC_IXDTRANSPORTEREDESPACHO","DOC_IDTRANSPORTEREDESPACHO");
    define("COL_FAV_DXOC_IXDTRANSPORTEDEPOSITO","DOC_IDTRANSPORTEDEPOSITO");
    define("COL_FAV_DXOC_DXOC_IDTRANSPORTE","DOC_IDTRANSPORTE");
    define("COL_FAV_DXOC_QUANTIDADE","DOC_QUANTIDADE");
    define("COL_FAV_DXOC_JXUSTIFICATIVA","DOC_JUSTIFICATIVA");
    define("COL_FAV_DXOC_IXDCONDICAOPAGAMENTO","N47_ID");

    $COL_FAV_DXOC_IXDTIPODEOPERACAOSTATUS = array(
        30 => 30,
        31 => 31,
        32 => 32,
        34 => 34,
        258 => 258
    );
}else if($gateSistema=="petrus"){
    define("TAB_FAV_DXOCUMENTOS","I57");

    define("COL_FAV_DXOC_DXATACONCLUSAO","I57_DATA_FATURAMENTO");
    define("COL_FAV_DXOC_DXATAEMISSAO","I57_DATA_EMISSAO");
    define("COL_FAV_DXOC_IXD","I57_ID");
    define("COL_FAV_DXOC_IXDEMPRESA","S1_ID");
    define("COL_FAV_DXOC_IXDPARTICIPANTE","I5_ID");
    define("COL_FAV_DXOC_IXDREPRESENTANTE","R4_ID");
    define("COL_FAV_DXOC_IXDTIPODEOPERACAO","DOC_IDTIPODEOPERACAO");
    define("COL_FAV_DXOC_IXDTIPODEOPERACAO_EX","35 AS DOC_IDTIPODEOPERACAO");
    define("COL_FAV_DXOC_IXDTIPODEOPERACAOSTATUS","I57_STATUS");// 30, 31, 32, 34 (Aberto, Concluído, Aprovado, Cancelado)
    define("COL_FAV_DXOC_NXRDOCUMENTO","I57_NRO_DOCUMENTO");
    define("COL_FAV_DXOC_PXERCENTUALDESCONTOFATURAMENTOESPECIAL","I57_TIPO_FATURAMENTO");
    define("COL_FAV_DXOC_IXDCONDICOESDEPAGAMENTO","N47_ID");
    define("COL_FAV_DXOC_IXDCONDICAODEPAGAMENTOESPECIAL","N47_ID_1");
    define("COL_FAV_DXOC_CXOMISSAO","I57_COMISSAO");
    define("COL_FAV_DXOC_IXDTRANSPORTEREDESPACHO","J2_ID_1");
    define("COL_FAV_DXOC_IXDTRANSPORTEDEPOSITO","J2_ID_1");
    define("COL_FAV_DXOC_DXOC_IDTRANSPORTE","J2_ID");
    define("COL_FAV_DXOC_QUANTIDADE","I57_VOLUMES");
    define("COL_FAV_DXOC_JXUSTIFICATIVA","I57_MOTIVO_CANCELAMENTO");
    define("COL_FAV_DXOC_IXDCONDICAOPAGAMENTO","N47_ID");

    $COL_FAV_DXOC_IXDTIPODEOPERACAOSTATUS = array(
        30 => "Novo",
        31 => "Concluido",
        32 => "Aprovado",
        34 => "Cancelado",
        258 => 258
    );
}