<?php
if($gateSistema=="rs"){
    define("TAB_PAG_DXOCUMENTOSDUPLICATASEXLENCODECONTAS","DOCUMENTOSDUPLICATASELENCODECONTAS");

    define("COL_PAG_DXUE_IXD","DUE_ID");
    define("COL_PAG_DXUE_IXDDUPLICATA","DUE_IDDUPLICATA");
    define("COL_PAG_DXUE_IXDELENCOCONTA","DUE_IDELENCOCONTA");
    define("COL_PAG_DXUE_VXALOR","DUE_VALOR");
}else if($gateSistema=="petrus"){
    define("TAB_PAG_DXOCUMENTOSDUPLICATASEXLENCODECONTAS","L70");

    define("COL_PAG_DXUE_IXD","L70_ID");
    define("COL_PAG_DXUE_IXDDUPLICATA","N9_ID");    
    define("COL_PAG_DXUE_IXDELENCOCONTA","L10_ID");
    define("COL_PAG_DXUE_VXALOR","L70_VALOR");
    define("COL_PAG_DXUE_IXDEMPRESA","S1_ID");
    define("COL_PAG_DXUE_DXESCRICAO","L70_DESCRICAO");
    define("COL_PAG_DXUE_DXATAINCLUSAO","L70_DATA_INCLUSAO");
    define("COL_PAG_DXUE_DXATA","L70_DATA");
    define("COL_PAG_DXUE_TXIPO","L70_TIPO");
    define("COL_PAG_DXUE_CXODIGO","L70_CODIGO");
    define("COL_PAG_DXUE_SXELECIONE","L70_SELECIONE");
}