<?php
if($gateSistema=="rs"){
    define("TAB_COM_DXOCUMENTOSIXTENS","DOCUMENTOSITENS");

    define("COL_COM_DXIT_DXESCRICAOPRINCIPAL","DIT_DESCRICAOPRINCIPAL");
    define("COL_COM_DXIT_IXD","DIT_ID");
    define("COL_COM_DXIT_IXDDXOCUMENTOS","DIT_IDDOCUMENTOS");
    define("COL_COM_DXIT_IXDIXTEM","DIT_IDITEM");
    define("COL_COM_DXIT_IXDTXIPODEOPERACAOSTATUS","DIT_IDTIPODEOPERACAOSTATUS");
    define("COL_COM_DXIT_PXESOBRUTO","DIT_PESOBRUTO");
    define("COL_COM_DXIT_QXTDCOMERCIAL","DIT_QTDCOMERCIAL");
    define("COL_COM_DXIT_VXALORUNITARIOCOMERCIAL","DIT_VALORUNITARIOCOMERCIAL");
    define("COL_COM_DXIT_NXRITEM","DIT_NRITEM");
    define("COL_COM_DXIT_VXALORDESCONTO","DIT_VALORDESCONTO");
    define("COL_COM_DXIT_CXODIGOPARTICIPANTE","DIT_CODIGOPARTICIPANTE");

    $COL_COM_DXIT_IXDTXIPODEOPERACAOSTATUS = array(
        30 => 30,
        31 => 31,
        32 => 32,
        34 => 34
    );
}else if($gateSistema=="petrus"){
    define("TAB_COM_DXOCUMENTOSIXTENS","I43");

    define("COL_COM_DXIT_DXESCRICAOPRINCIPAL","I43_DESCRICAO");
    define("COL_COM_DXIT_IXD","I43_ID");
    define("COL_COM_DXIT_IXDDXOCUMENTOS","I14_ID");
    define("COL_COM_DXIT_IXDIXTEM","G6_ID");
    define("COL_COM_DXIT_IXDTXIPODEOPERACAOSTATUS","");// NÃO TEM ESSE CAMPO NO PETRUS
    define("COL_COM_DXIT_PXESOBRUTO","I43_PESO_BRUTO");
    define("COL_COM_DXIT_QXTDCOMERCIAL","I43_QTD");
    define("COL_COM_DXIT_VXALORUNITARIOCOMERCIAL","I43_VALOR_UNITARIO");
    define("COL_COM_DXIT_NXRITEM","I43_ITEM");
    define("COL_COM_DXIT_VXALORDESCONTO","I43_VALOR_DESCONTO");
    define("COL_COM_DXIT_CXODIGOPARTICIPANTE","I5_ID");
}