<?php
if($gateSistema=="rs"){
    define("TAB_VEN_DXOCUMENTOSIXTENS","DOCUMENTOSITENS");

    define("COL_DXIT_DXESCRICAOPRINCIPAL","DIT_DESCRICAOPRINCIPAL");
    define("COL_DXIT_IXD","DIT_ID");
    define("COL_DXIT_IXDDXOCUMENTOS","DIT_IDDOCUMENTOS");
    define("COL_DXIT_IXDIXTEM","DIT_IDITEM");
    define("COL_DXIT_IXDTXIPODEOPERACAOSTATUS","DIT_IDTIPODEOPERACAOSTATUS");
    define("COL_DXIT_PXESOLIQUIDO","DIT_PESOLIQUIDO");
    define("COL_DXIT_PXESOBRUTO","DIT_PESOBRUTO");
    define("COL_DXIT_QXTDCOMERCIAL","DIT_QTDCOMERCIAL");
    define("COL_DXIT_VXALORUNITARIOCOMERCIAL","DIT_VALORUNITARIOCOMERCIAL");
    define("COL_DXIT_NXRITEM","DIT_NRITEM");
    define("COL_DXIT_VXALORDESCONTO","DIT_VALORDESCONTO");
    define("COL_DXIT_QXTDFATURADA","DIT_QTDFATURADA");
    define("COL_DXIT_VXALORFRETE","DIT_VALORFRETE");
    define("COL_DXIT_CXODIGOPARTICIPANTE","DIT_CODIGOPARTICIPANTE");
    define("COL_DXIT_IXTEMCOMPOETOTALNOTA","DIT_ITEMCOMPOETOTALNOTA");
    define("COL_DXIT_DXATAMODIFICACAO","DIT_DATAMODIFICACAO");
    define("COL_DXIT_VXOLUME","DIT_VOLUME");
    define("COL_DXIT_IXDOPERACAOFISCAL","DIT_IDOPERACAOFISCAL");

    $COL_DXIT_IXDTXIPODEOPERACAOSTATUS = array(
        30 => 30,
        31 => 31,
        32 => 32,
        34 => 34
    );
}else if($gateSistema=="petrus"){
    define("TAB_VEN_DXOCUMENTOSIXTENS","R49");

    define("COL_DXIT_DXESCRICAOPRINCIPAL","R49_DESCRICAO");
    define("COL_DXIT_IXD","R49_ID");
    define("COL_DXIT_IXDDXOCUMENTOS","R13_ID");
    define("COL_DXIT_IXDIXTEM","G6_ID");
    define("COL_DXIT_IXDTXIPODEOPERACAOSTATUS","");// NÃO TEM ESSE CAMPO NO PETRUS
    define("COL_DXIT_PXESOLIQUIDO","R49_PESO_LIQUIDO");
    define("COL_DXIT_PXESOBRUTO","R49_PESO_BRUTO");
    define("COL_DXIT_QXTDCOMERCIAL","R49_QTD");
    define("COL_DXIT_VXALORUNITARIOCOMERCIAL","R49_VALOR_UNITARIO");
    define("COL_DXIT_NXRITEM","R49_ITEM");
    define("COL_DXIT_VXALORDESCONTO","R49_VALOR_DESCONTO");
    define("COL_DXIT_QXTDFATURADA","R49_QTD");
    define("COL_DXIT_VXALORFRETE","R49_VALOR_FRETE");
    define("COL_DXIT_CXODIGOPARTICIPANTE","R2_ID");
    define("COL_DXIT_IXTEMCOMPOETOTALNOTA","R49_COMPOE_TOTAL_NF");
    define("COL_DXIT_DXATAMODIFICACAO","R49_DATA_INCLUSAO");
    define("COL_DXIT_VXOLUME","R49_VOLUME");
    define("COL_DXIT_IXDOPERACAOFISCAL","R49_CFOP");
    define("COL_DXIT_VALOR_TOTAL","R49_VALOR_TOTAL");
    define("COL_DXIT_R49_PRODUTO","R49_PRODUTO");    
    define("COL_DXIT_R49_SUBTOTAL","R49_SUBTOTAL");
}