<?php
if($gateSistema=="rs"){
    define("TAB_PAG_DXOCUMENTOSDXUPLICATAS","DOCUMENTOSDUPLICATAS");

    define("COL_PAG_DXDU_IXD","DDU_ID");
    define("COL_PAG_DXDU_IXDDOCUMENTOS","DDU_IDDOCUMENTOS");
    define("COL_PAG_DXDU_IXDDOCUMENTOS_B","DDU_IDDOCUMENTOS");
    define("COL_PAG_DXDU_NXRDOCUMENTO","DDU_NRDOCUMENTO"); 
    define("COL_PAG_DXDU_IXDPARTICIPANTE","DDU_IDPARTICIPANTE");
    define("COL_PAG_DXDU_DXATAEMISSAO","DDU_DATAEMISSAO");
    define("COL_PAG_DXDU_DXATAVENCIMENTO","DDU_DATAVENCIMENTO");
    define("COL_PAG_DXDU_DXATAULTIMABAIXA","DDU_DATAULTIMABAIXA");
    define("COL_PAG_DXDU_VXALORORIGINAL","DDU_VALORORIGINAL");
    define("COL_PAG_DXDU_IXDEMPRESA","DDU_IDEMPRESA");
    define("COL_PAG_DXDU_SXTATUS","DDU_STATUS");
    define("COL_PAG_DXDU_CXONTA_BXANCARIA","N49_ID");
    define("COL_PAG_DXDU_DXESCRICAO","N9_DESCRICAO");
    define("COL_PAG_DXDU_VXALOR_SALDO","N9_VALOR_SALDO");
    define("COL_PAG_DXDU_N9_TIPO","N9_TIPO");
}else if($gateSistema=="petrus"){
    define("TAB_PAG_DXOCUMENTOSDXUPLICATAS","N9");

    define("COL_PAG_DXDU_IXD","N9_ID");
    define("COL_PAG_DXDU_IXDDOCUMENTOS","I11_ID"); 
    define("COL_PAG_DXDU_IXDDOCUMENTOS_B","I57_ID");
    define("COL_PAG_DXDU_NXRDOCUMENTO","N9_NUMERO_DOCUMENTO"); 
    define("COL_PAG_DXDU_IXDPARTICIPANTE","I5_ID"); 
    define("COL_PAG_DXDU_DXATAEMISSAO","N9_DATA_EMISSAO");
    define("COL_PAG_DXDU_DXATAVENCIMENTO","N9_DATA_VENCIMENTO");
    define("COL_PAG_DXDU_DXATAULTIMABAIXA","N9_DATA_PAGAMENTO");
    define("COL_PAG_DXDU_VXALORORIGINAL","N9_VALOR_TITULO");
    define("COL_PAG_DXDU_IXDEMPRESA","S1_ID");
    define("COL_PAG_DXDU_SXTATUS","N9_STATUS");
    define("COL_PAG_DXDU_CXONTA_BXANCARIA","N49_ID");
    define("COL_PAG_DXDU_DXESCRICAO","N9_DESCRICAO");
    define("COL_PAG_DXDU_VXALOR_SALDO","N9_VALOR_SALDO");
    define("COL_PAG_DXDU_N9_TIPO","N9_TIPO");
}