<?php
if($gateSistema=="rs"){
    define("TAB_FTR_DXOCUMENTOSIXTENS","DOCUMENTOSITENS");

    define("COL_FTR_DXIT_DXESCRICAOPRINCIPAL","DIT_DESCRICAOPRINCIPAL");
    define("COL_FTR_DXIT_IXD","DIT_ID");
    define("COL_FTR_DXIT_IXDDXOCUMENTOS","DIT_IDDOCUMENTOS");
    define("COL_FTR_DXIT_IXDIXTEM","DIT_IDITEM");
    define("COL_FTR_DXIT_IXDTXIPODEOPERACAOSTATUS","DIT_IDTIPODEOPERACAOSTATUS");
    define("COL_FTR_DXIT_PXESOBRUTO","DIT_PESOBRUTO");
    define("COL_FTR_DXIT_QXTDCOMERCIAL","DIT_QTDCOMERCIAL");
    define("COL_FTR_DXIT_VXALORUNITARIOCOMERCIAL","DIT_VALORUNITARIOCOMERCIAL");
    define("COL_FTR_DXIT_NXRITEM","DIT_NRITEM");
    define("COL_FTR_DXIT_VXALORDESCONTO","DIT_VALORDESCONTO");
    define("COL_FTR_DXIT_CXODIGOPARTICIPANTE","DIT_CODIGOPARTICIPANTE");

    $COL_FTR_DXIT_IXDTXIPODEOPERACAOSTATUS = array(
        30 => 30,
        31 => 31,
        32 => 32,
        34 => 34
    );
}else if($gateSistema=="petrus"){
    define("TAB_FTR_DXOCUMENTOSIXTENS","I46");

    define("COL_FTR_DXIT_DXESCRICAOPRINCIPAL","I46_DESCRICAO");
    define("COL_FTR_DXIT_IXD","I46_ID");
    define("COL_FTR_DXIT_IXDDXOCUMENTOS","I11_ID");
    define("COL_FTR_DXIT_IXDIXTEM","G6_ID");
    define("COL_FTR_DXIT_IXDTXIPODEOPERACAOSTATUS","");// NÃO TEM ESSE CAMPO NO PETRUS
    define("COL_FTR_DXIT_PXESOBRUTO","I46_PESO_BRUTO");
    define("COL_FTR_DXIT_QXTDCOMERCIAL","I46_QTD");
    define("COL_FTR_DXIT_VXALORUNITARIOCOMERCIAL","I46_VALOR_UNITARIO");
    define("COL_FTR_DXIT_NXRITEM","I46_ITEM");
    define("COL_FTR_DXIT_VXALORDESCONTO","I46_VALOR_DESCONTO");
    define("COL_FTR_DXIT_CXODIGOPARTICIPANTE","I5_ID");
}