<?php
if($gateSistema=="rs"){
    define("TAB_PAG_DXOCUMENTOSDUPLICATASCXOMPROVANTESBAIXA","DOCUMENTOSDUPLICATASCOMPROVANTESBAIXA");

    define("COL_PAG_DXDC_EXSTORNADO","DDC_ESTORNADO");
    define("COL_PAG_DXDC_IXD","DDC_ID");
}else if($gateSistema=="petrus"){
    define("TAB_PAG_DXOCUMENTOSDUPLICATASCXOMPROVANTESBAIXA","N13");

    define("COL_PAG_DXDC_EXSTORNADO","N13_ESTORNADO");
    define("COL_PAG_DXDC_IXD","N13_ID");
}