<?php
if($gateSistema=="rs"){
    define("TAB_MXOVIMENTACAOBANCARIAEXLENCOCONTAS","MOVIMENTACAOBANCARIAELENCOCONTAS");

    define("COL_MXBE_IXD","MBE_ID");
    define("COL_MXBE_IXDMOVIMENTACAOBANCARIA","MBE_IDMOVIMENTACAOBANCARIA");
    define("COL_MXBE_IXDELENCODECONTA","MBE_IDELENCODECONTA");
    define("COL_MXBE_VXALOR","MBE_VALOR");
}else if($gateSistema=="petrus"){
    define("TAB_MXOVIMENTACAOBANCARIAEXLENCOCONTAS","L4");

    define("COL_MXBE_IXD","L4_ID");
    define("COL_MXBE_IXDMOVIMENTACAOBANCARIA","N91_ID");    
    define("COL_MXBE_IXDELENCODECONTA","L10_ID");
    define("COL_MXBE_VXALOR","L4_VALOR");
    define("COL_MXBE_IXDEMPRESA","S1_ID");
    define("COL_MXBE_DXESCRICAO","L4_DESCRICAO");
    define("COL_MXBE_DXATAINCLUSAO","L4_DATA_INCLUSAO");
    define("COL_MXBE_DXATA","L4_DATA");
    define("COL_MXBE_TXIPO","L4_TIPO");
    define("COL_MXBE_CXODIGO","L4_CODIGO");
    define("COL_MXBE_SXELECIONE","L4_SELECIONE");
}