<?php
if($gateSistema=="rs"){
    define("TAB_MXOVIMENTACAOBANCARIA","MOVIMENTACAOBANCARIA");

    define("COL_MXVB_IXD","MVB_ID");
    define("COL_MXVB_IXDCONTABANCARIA","MVB_IDCONTABANCARIA");
    define("COL_MXVB_DXATAEMISSAO","MVB_DATAEMISSAO");
    define("COL_MXVB_VXALOR","MVB_VALOR");
    define("COL_MXVB_HXISTORICO","MVB_HISTORICO");
    define("COL_MXVB_IXDCOMPROVANTE","MVB_IDCOMPROVANTE");
    define("COL_MXVB_IXDOPERACAOBANCARIA","MVB_IDOPERACAOBANCARIA");
    define("COL_MXVB_IXDEMPRESA","MVB_IDEMPRESA");

    define("COL_MXVB_IDCHEQUE_EX",",MVB_IDCHEQUE");

    $COL_MXVB_IXDOPERACAOBANCARIA = array(
        1 => 1,
        2 => 2
    );
}else if($gateSistema=="petrus"){
    define("TAB_MXOVIMENTACAOBANCARIA","N91");

    define("COL_MXVB_IXD","N91_ID");
    define("COL_MXVB_IXDCONTABANCARIA","N90_ID");
    define("COL_MXVB_DXATAEMISSAO","N91_DATA");
    define("COL_MXVB_VXALOR","N91_VALOR");
    define("COL_MXVB_HXISTORICO","N91_DESCRICAO");
    define("COL_MXVB_IXDCOMPROVANTE","N37_ID");
    define("COL_MXVB_IXDOPERACAOBANCARIA","N91_TIPO");
    define("COL_MXVB_IXDRECEBIMENTO_MOVIMENTACAO_BANCARIA","N43_ID");
    define("COL_MXVB_IXDPAGAMENTOS_MOVIMENTACAO_BANCARIA","N13_ID");
    define("COL_MXVB_SXTATUS","N91_STATUS");
    define("COL_MXVB_IXDRECEBIMENTOS","N22_ID");
    define("COL_MXVB_IXDEMPRESA","S1_ID");

    define("COL_MXVB_IDCHEQUE_EX","");

    $COL_MXVB_IXDOPERACAOBANCARIA = array(
        1 => "C",
        2 => "D"
    );
}