<?php
if($gateSistema=="rs"){
    define("TAB_CLI_PXARTICIPANTES","PARTICIPANTES");

    define("COL_CLI_PXAR_IXD","PAR_ID"); 
    define("COL_CLI_PXAR_IXDREPRESENTANTEPRIMARIO","PAR_IDREPRESENTANTEPRIMARIO"); 
    define("COL_CLI_PXAR_CXODIGOINTERNO","PAR_CODIGOINTERNO"); 
    define("COL_CLI_PXAR_CXPFCNPJ","PAR_CPFCNPJ"); 
    define("COL_CLI_PXAR_DXATADECADASTRO","PAR_DATADECADASTRO"); 
    define("COL_CLI_PXAR_IXDTIPODEOPERACAOSTATUS","PAR_IDTIPODEOPERACAOSTATUS");
    define("COL_CLI_PXAR_NXOMEFANTASIA","PAR_NOMEFANTASIA"); 
    define("COL_CLI_PXAR_RXAZAOSOCIAL","PAR_RAZAOSOCIAL"); 
    define("COL_CLI_PXAR_RXGINSCRICAOESTADUAL","PAR_RGINSCRICAOESTADUAL");
    define("COL_CLI_PXAR_OXBSERVACAO","PAR_OBSERVACAO");
    define("COL_CLI_PXAR_IXDREGIMETRIBUTARIO","PAR_IDREGIMETRIBUTARIO");
    define("COL_CLI_PXAR_FXISCALSUFRAMA","PAR_FISCALSUFRAMA");
    define("COL_CLI_PXAR_DXATAABERTURANASCIMENTO","PAR_DATAABERTURANASCIMENTO");
    define("COL_CLI_PXEN_IXDMUNICIPIO","PEN_IDMUNICIPIO"); 
    define("COL_CLI_PXAR_TXIPOPESSOA","PAR_TIPOPESSOA");
    define("COL_CLI_PXAR_IXSENTOICMSST","PAR_ISENTOICMSST"); 
    define("COL_CLI_PXAR_SXUSPENSAOIPI","PAR_SUSPENSAOIPI");
    define("COL_CLI_PXEN_LXOGRADOURO","PEN_LOGRADOURO");
    define("COL_CLI_PXEN_BXAIRRO","PEN_BAIRRO");
    define("COL_CLI_PXEN_NXUMERO","PEN_NUMERO");
    define("COL_CLI_PXEN_CXOMPLEMENTO","PEN_COMPLEMENTO");
    define("COL_CLI_PXEN_CXEP","PEN_CEP");
    define("COL_CLI_PXEN_FXONE","PCO_CONTATO");
    define("COL_CLI_PXEN_EXMAIL","PCO_EMAIL");

    $COL_CLI_PXAR_IXDTIPODEOPERACAOSTATUS = array(
        140 => 140,
        144 => 144
    );

    define("TAB_REP_PXARTICIPANTES","PARTICIPANTES");

    define("COL_REP_PXAR_IXD","PAR_ID"); 
    define("COL_REP_PXAR_CXODIGOINTERNO","PAR_CODIGOINTERNO"); 
    define("COL_REP_PXAR_CXPFCNPJ","PAR_CPFCNPJ");
    define("COL_REP_PXAR_DXATADECADASTRO","PAR_DATADECADASTRO"); 
    define("COL_REP_PXAR_IXDTIPODEOPERACAOSTATUS","PAR_IDTIPODEOPERACAOSTATUS");
    define("COL_REP_PXAR_NXOMEFANTASIA","PAR_NOMEFANTASIA"); 
    define("COL_REP_PXAR_RXAZAOSOCIAL","PAR_RAZAOSOCIAL"); 
    define("COL_REP_PXEN_LXOGRADOURO","PEN_LOGRADOURO");
    define("COL_REP_PXEN_BXAIRRO","PEN_BAIRRO");
    define("COL_REP_PXEN_NXUMERO","PEN_NUMERO");
    define("COL_REP_PXEN_CXOMPLEMENTO","PEN_COMPLEMENTO");
    define("COL_REP_PXEN_CXEP","PEN_CEP");
    define("COL_REP_PXEN_IXDMUNICIPIO","PEN_IDMUNICIPIO");

    $COL_REP_PXAR_IXDTIPODEOPERACAOSTATUS = array(
        140 => 140,
        144 => 144
    );

    define("TAB_TRA_PXARTICIPANTES","PARTICIPANTES");

    define("COL_TRA_PXAR_IXD","PAR_ID"); 
    define("COL_TRA_PXAR_CXODIGOINTERNO","PAR_CODIGOINTERNO"); 
    define("COL_TRA_PXAR_CXPFCNPJ","PAR_CPFCNPJ");
    define("COL_TRA_PXAR_DXATADECADASTRO","PAR_DATADECADASTRO"); 
    define("COL_TRA_PXAR_IXDTIPODEOPERACAOSTATUS","PAR_IDTIPODEOPERACAOSTATUS");
    define("COL_TRA_PXAR_NXOMEFANTASIA","PAR_NOMEFANTASIA"); 
    define("COL_TRA_PXAR_RXAZAOSOCIAL","PAR_RAZAOSOCIAL"); 
    define("COL_TRA_PXEN_LXOGRADOURO","PEN_LOGRADOURO");
    define("COL_TRA_PXEN_BXAIRRO","PEN_BAIRRO");
    define("COL_TRA_PXEN_NXUMERO","PEN_NUMERO");
    define("COL_TRA_PXEN_CXOMPLEMENTO","PEN_COMPLEMENTO");
    define("COL_TRA_PXEN_CXEP","PEN_CEP");
    define("COL_TRA_PXEN_IXDMUNICIPIO","PEN_IDMUNICIPIO");

    $COL_TRA_PXAR_IXDTIPODEOPERACAOSTATUS = array(
        140 => 140,
        144 => 144
    );

    define("TAB_FOR_PXARTICIPANTES","PARTICIPANTES");

    define("COL_FOR_PXAR_IXD","PAR_ID"); 
    define("COL_FOR_PXAR_CXODIGOINTERNO","PAR_CODIGOINTERNO"); 
    define("COL_FOR_PXAR_CXPFCNPJ","PAR_CPFCNPJ");
    define("COL_FOR_PXAR_DXATADECADASTRO","PAR_DATADECADASTRO"); 
    define("COL_FOR_PXAR_IXDTIPODEOPERACAOSTATUS","PAR_IDTIPODEOPERACAOSTATUS");
    define("COL_FOR_PXAR_NXOMEFANTASIA","PAR_NOMEFANTASIA"); 
    define("COL_FOR_PXAR_RXAZAOSOCIAL","PAR_RAZAOSOCIAL"); 
    define("COL_FOR_PXEN_LXOGRADOURO","PEN_LOGRADOURO");
    define("COL_FOR_PXEN_BXAIRRO","PEN_BAIRRO");
    define("COL_FOR_PXEN_NXUMERO","PEN_NUMERO");
    define("COL_FOR_PXEN_CXOMPLEMENTO","PEN_COMPLEMENTO");
    define("COL_FOR_PXEN_CXEP","PEN_CEP");
    define("COL_FOR_PXEN_IXDMUNICIPIO","PEN_IDMUNICIPIO");
    define("COL_FOR_EMPRESA","PAR_IDEMPRESA");

    $COL_FOR_PXAR_IXDTIPODEOPERACAOSTATUS = array(
        140 => 140,
        144 => 144
    );
}else if($gateSistema=="petrus"){
    define("TAB_CLI_PXARTICIPANTES","R2");

    define("COL_CLI_PXAR_IXD","R2_ID"); 
    define("COL_CLI_PXAR_IXDREPRESENTANTEPRIMARIO","R4_ID"); 
    define("COL_CLI_PXAR_CXODIGOINTERNO","R2_CODIGO"); 
    define("COL_CLI_PXAR_CXPFCNPJ","R2_CNPJ_CPF");
    define("COL_CLI_PXAR_DXATADECADASTRO","R2_DATA_INCLUSAO");
    define("COL_CLI_PXAR_IXDTIPODEOPERACAOSTATUS","R2_STATUS");
    define("COL_CLI_PXAR_NXOMEFANTASIA","R2_NOME_FANTASIA"); 
    define("COL_CLI_PXAR_RXAZAOSOCIAL","R2_NOME"); 
    define("COL_CLI_PXAR_RXGINSCRICAOESTADUAL","R2_IE_RG");
    define("COL_CLI_PXAR_OXBSERVACAO","R2_OBS");
    define("COL_CLI_PXAR_IXDREGIMETRIBUTARIO","X25_ID");
    define("COL_CLI_PXAR_FXISCALSUFRAMA","R2_SUFRAMA");
    define("COL_CLI_PXAR_DXATAABERTURANASCIMENTO","R2_DATA_ABERTURA");
    define("COL_CLI_PXEN_IXDMUNICIPIO","X4_ID");
    define("COL_CLI_PXAR_TXIPOPESSOA","R2_TIPO_PESSOA");
    define("COL_CLI_PXAR_IXSENTOICMSST","R2_ICMS_ISENTO");
    define("COL_CLI_PXAR_SXUSPENSAOIPI","R2_IPI_ISENTO"); 
    define("COL_CLI_PXEN_LXOGRADOURO","R2_LOGRADOURO");
    define("COL_CLI_PXEN_BXAIRRO","R2_BAIRRO");
    define("COL_CLI_PXEN_NXUMERO","R2_NUMERO");
    define("COL_CLI_PXEN_CXOMPLEMENTO","R2_COMPLEMENTO");
    define("COL_CLI_PXEN_CXEP","R2_CEP");
    define("COL_CLI_PXEN_FXONE","R2_FONE_1");
    define("COL_CLI_PXEN_EXMAIL","R2_EMAIL");

    $COL_CLI_PXAR_IXDTIPODEOPERACAOSTATUS = array(
        140 => "Ativo",
        144 => "Bloqueado"
    );

    define("TAB_REP_PXARTICIPANTES","R4");

    define("COL_REP_PXAR_IXD","R4_ID"); 
    define("COL_REP_PXAR_CXODIGOINTERNO","R4_CODIGO"); 
    define("COL_REP_PXAR_CXPFCNPJ","R4_CNPJ_CPF");
    define("COL_REP_PXAR_DXATADECADASTRO","R4_DATA_INCLUSAO");
    define("COL_REP_PXAR_IXDTIPODEOPERACAOSTATUS","R4_STATUS");
    define("COL_REP_PXAR_NXOMEFANTASIA","R4_NOME_FANTASIA"); 
    define("COL_REP_PXAR_RXAZAOSOCIAL","R4_NOME"); 
    define("COL_REP_PXEN_LXOGRADOURO","R4_LOGRADOURO");
    define("COL_REP_PXEN_BXAIRRO","R4_BAIRRO");
    define("COL_REP_PXEN_NXUMERO","R4_NUMERO");
    define("COL_REP_PXEN_CXOMPLEMENTO","R4_COMPLEMENTO");
    define("COL_REP_PXEN_CXEP","R4_CEP");
    define("COL_REP_PXEN_IXDMUNICIPIO","X4_ID");

    $COL_REP_PXAR_IXDTIPODEOPERACAOSTATUS = array(
        140 => "Ativo",
        144 => "Bloqueado"
    );

    define("TAB_TRA_PXARTICIPANTES","J2");

    define("COL_TRA_PXAR_IXD","J2_ID"); 
    define("COL_TRA_PXAR_CXODIGOINTERNO","J2_CODIGO"); 
    define("COL_TRA_PXAR_CXPFCNPJ","J2_CNPJ_CPF");
    define("COL_TRA_PXAR_DXATADECADASTRO","J2_DATA_INCLUSAO");
    define("COL_TRA_PXAR_IXDTIPODEOPERACAOSTATUS","J2_STATUS");
    define("COL_TRA_PXAR_NXOMEFANTASIA","J2_NOME_FANTASIA"); 
    define("COL_TRA_PXAR_RXAZAOSOCIAL","J2_NOME"); 
    define("COL_TRA_PXEN_LXOGRADOURO","J2_LOGRADOURO");
    define("COL_TRA_PXEN_BXAIRRO","J2_BAIRRO");
    define("COL_TRA_PXEN_NXUMERO","J2_NUMERO");
    define("COL_TRA_PXEN_CXOMPLEMENTO","J2_COMPLEMENTO");
    define("COL_TRA_PXEN_CXEP","J2_CEP");
    define("COL_TRA_PXEN_IXDMUNICIPIO","X4_ID");

    $COL_TRA_PXAR_IXDTIPODEOPERACAOSTATUS = array(
        140 => "Ativo",
        144 => "Bloqueado"
    );

    define("TAB_FOR_PXARTICIPANTES","I5");

    define("COL_FOR_PXAR_IXD","I5_ID"); 
    define("COL_FOR_PXAR_CXODIGOINTERNO","I5_CODIGO"); 
    define("COL_FOR_PXAR_CXPFCNPJ","I5_CNPJ_CPF");
    define("COL_FOR_PXAR_DXATADECADASTRO","I5_DATA_INCLUSAO");
    define("COL_FOR_PXAR_IXDTIPODEOPERACAOSTATUS","I5_STATUS");
    define("COL_FOR_PXAR_NXOMEFANTASIA","I5_NOME_FANTASIA"); 
    define("COL_FOR_PXAR_RXAZAOSOCIAL","I5_NOME"); 
    define("COL_FOR_PXEN_LXOGRADOURO","I5_LOGRADOURO");
    define("COL_FOR_PXEN_BXAIRRO","I5_BAIRRO");
    define("COL_FOR_PXEN_NXUMERO","I5_NUMERO");
    define("COL_FOR_PXEN_CXOMPLEMENTO","I5_COMPLEMENTO");
    define("COL_FOR_PXEN_CXEP","I5_CEP");
    define("COL_FOR_PXEN_IXDMUNICIPIO","X4_ID");
    define("COL_FOR_EMPRESA","S1_ID");

    $COL_FOR_PXAR_IXDTIPODEOPERACAOSTATUS = array(
        140 => "Ativo",
        144 => "Bloqueado"
    );
}